CREATE TABLE [dbo].[User]
(
	[Name] NVARCHAR(50) NOT NULL PRIMARY KEY,
	[Password] NVARCHAR(50) 
		ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = CEK_Auto1,  
        ENCRYPTION_TYPE = RANDOMIZED,  
        ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') NOT NULL
)
